title: EvBoo Documentation

remote_theme: readthedocs/sphinx_rtd_theme

# Set a path/url to a logo that will be displayed instead of the title
logo: "/images/Cluster.png"

# Exclude the main readme.md file

exclude: "/README.md"
